apiVersion: v1
kind: Service
metadata:
  name: bee-stack-agent
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: bee-stack
    app.kubernetes.io/instance: agent
