apiVersion: v1
kind: Service
metadata:
  name: bee-stack-observe
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: bee-stack
    app.kubernetes.io/instance: observe
