apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-bee-stack
  labels:
    app.kubernetes.io/name: bee-stack
    app.kubernetes.io/instance: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bee-stack
      app.kubernetes.io/instance: ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bee-stack
        app.kubernetes.io/instance: ui
    spec:
      serviceAccountName: bee-stack-agent
      containers:
        - name: bee-stack-ui
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          env:
            - name: NEXTAUTH_URL
              value: http://bee-stack-ui:3000
            - name: NEXTAUTH_SECRET
              value: top-secret
            - name: API_URL
              value: http://bee-stack-agent:4000
            - name: DUMMY_JWT_TOKEN
              value: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0IiwicHJlZmVycmVkX3VzZXJuYW1lIjoiVGVzdCBVc2VyIiwiZW1haWwiOiJ0ZXN0QGVtYWlsLmNvbSIsImlhdCI6MTUxNjIzOTAyMiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3QiLCJhdWQiOiJiZWUtdGVzdCJ9.vwkGnl7lBbzJYk6BtoW3VoA3mnNJVI-nDQU8aK7zOH-rkf2pn5cn6CKwpq7enDInIXro8WtBLNZP8Nr8GQIZKahICuP3YrPRmzv7YIW8LuXKnx1hycg5OAtj0OtQi5FYwwCxTYW9pBF2it7XwQSBcW7yYsOrvgs7jVhThCOsavX0YiAROxZIhk1idZT4Pl3egfUI_dy9iBxcn7xocTnos-94wqJNt8oCVgB8ynj75yJFHJbiQ-9Tym_V3LcMHoEyv67Jzie8KugCgdpuF6EbQqcyfYJ83q5jJpR2LiuWMuGsNSbjjDY-f1vCSMo9L9-R8KFrDylT_BzLvRBswOzW7A
          ports:
          - containerPort: 3000
            name: http
            protocol: TCP
